# Site settings
locale                    : "en-US"
title                     : "Andrew David Wong"
title_separator           : "-"
name                      : "Andrew David Wong"
description               : "Andrew David Wong is the CEO of Invisible Things Lab and the Community Manager of the Qubes OS Project."
url                       : "https://andrewdavidwong.com"
baseurl                   :
repository                : "andrewdwong/andrewdavidwong.com"
project_repo_path         : "https://github.com/andrewdwong"
project_repo_site         : "/andrewdavidwong.com"
teaser                    : "/adw.jpg"
# breadcrumbs             : false # true, false (default)
words_per_minute          : 200
comments:
  provider                : "staticman"
staticman:
  allowedFields           : ['name', 'email', 'url', 'message']
  branch                  : "master"
  commitMessage           : "Add new comment"
  filename                : comment-{@timestamp}
  format                  : "yml"
  moderation              : true
  path                    : "_data/comments/{options.slug}"
  requiredFields          : ['name', 'message']
  transforms:
    email                 : "md5"
  generatedFields:
    date:
      type                : "date"
      options:
        format            : "iso8601"
atom_feed:
  path                    : # blank (default) uses feed.xml

# SEO
bing_site_verification    :
alexa_site_verification   :
yandex_site_verification  :

# Social
twitter:
  username                : andrewdavidwong
facebook:
  username                : andrewdavidwong.adw
og_image                  : "/adw.jpg"
social:
  type                    : Person
  links:
    - "https://keybase.io/adw"
    - "https://github.com/andrewdavidwong"
    - "https://twitter.com/andrewdavidwong"
    - "https://www.facebook.com/andrewdavidwong.adw"
    - "https://www.linkedin.com/in/andrewdwong"

# Site Author
author:
  name                    : "Andrew David Wong"
  avatar                  : "/adw.jpg"
  uri                     : "https://andrewdavidwong.com"
  bio                     : CEO of Invisible Things Lab and Community Manager of the Qubes OS Project.
  email                   : adw@andrewdavidwong.com
  email                   : adw@invisiblethingslab.com
  email                   : adw@qubes-os.org
  github                  : andrewdavidwong
  twitter                 : andrewdavidwong
  keybase                 : adw
  linkedin                : andrewdwong

# Reading Files
include:
  - _pages
exclude:
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding                  : "utf-8"
markdown_ext              : "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown                  : kramdown
highlighter               : rouge
lsi                       : false
excerpt_separator         : "\n\n"
incremental               : false

# Markdown Processing
kramdown:
  input                   : GFM
  hard_wrap               : false
  auto_ids                : true
  footnote_nr             : 1
  entity_output           : as_char
  toc_levels              : 1..6
  smart_quotes            : lsquo,rsquo,ldquo,rdquo
  enable_coderay          : false

# Sass/SCSS
sass:
  sass_dir                : _sass
  style                   : compressed

# Outputting
permalink                 : /:title
paginate                  : 5
paginate_path             : /page:num
timezone                  : UTC

# Plugins
gems:
  - jekyll-redirect-from
  - jekyll-minibundle
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Mimic GitHug Pages with `--safe`
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type                    : liquid
  path                    : /categories
tag_archive:
  type                    : liquid
  path                    : /tags

# HTML Compression
compress_html:
  clippings               : all
  comments                : ["<!-- ", " -->"]
  endings                 : all
  blanklines              : false
  startings               : [html, head, body]
  ignore:
    envs                  : development

# Defaults
defaults:
  # _posts
  - scope:
      path                : ""
      type                : posts
    values:
      layout              : single
      author_profile      : true
      read_time           : false
      comments            : true
      share               : true
      related             : false
